/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthModal: typeof import('./../components/auth-modal/index.vue')['default']
    FgNavbar: typeof import('./../components/fg-navbar/fg-navbar.vue')['default']
    Input: typeof import('./../components/input/index.vue')['default']
    MessageDisplay: typeof import('./../components/message-display/index.vue')['default']
    ProfileGuideCard: typeof import('./../components/profile-guide-card/index.vue')['default']
    TimePicker: typeof import('./../components/time-picker/index.vue')['default']
  }
}
